name: KiranProjectStagingForImport
description: ''
version: 0.0.1
author: kiranadmin@prophecy.io
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: kiranprojectstagingforimport
  parentArtefactID: kiranadminprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2024-01-09 11:05:35'
pipelines:
  pipelines/p1:
    name: p1
    description: ''
    author: kiranadmin@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-01-09 11:05:35'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-01-09 11:05:35'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '42':
    projectUID: 1
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/9gt3CHHz_team_9/pJIIcs5r_project_42.git&subPath=
    version: 0.0.7
    isDefault: true
    author: null
    createdAt: '2024-01-09 11:05:24'
  '43':
    projectUID: 2
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/9gt3CHHz_team_9/pJIIcs5r_project_43.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2024-01-09 11:05:24'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
