name: KiranProjectStagingForImportScala
description: ''
version: 0.0.1
author: kiranadmin@prophecy.io
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: kiranprojectstagingforimportscala
  parentArtefactID: kiranadminprophecyioteam
  buildSystem: maven
  author: null
  createdAt: '2024-01-09 11:24:45'
pipelines:
  pipelines/p1:
    name: p1
    description: ''
    author: kiranadmin@prophecy.io
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2024-01-09 11:24:45'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.0.4
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-01-09 11:24:45'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '39':
    projectUID: 39
    projectName: ProphecySparkBasicsScala
    repositoryPath: gitUri=http://gitserver:3000/9gt3CHHz_team_9/pJIIcs5r_project_39.git&subPath=
    version: 0.0.6
    isDefault: true
    author: null
    createdAt: '2024-01-09 11:24:37'
  '40':
    projectUID: 40
    projectName: ProphecyWarehouseScala
    repositoryPath: gitUri=http://gitserver:3000/9gt3CHHz_team_9/pJIIcs5r_project_40.git&subPath=
    version: 0.0.3
    isDefault: true
    author: null
    createdAt: '2024-01-09 11:24:37'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
